default:
  optimizer: sgd
  trasform: None
  # Continual learning From NEST
  alpha: 0.1
  lr: 0.001
  # n_epochs: 30
  n_epochs: 10
  batch_size: 32

  # SRNN architecture
  n_in: 1196
  srnn_hidden_size: 150
  # srnn_hidden_size: 500
  n_out: 10
  thr: .6
  tau_m: 30
  tau_o: 100
  b_o: 0.0
  dt: 1.
  n_t: 100
  seq_len_train: 100
  seq_len_test: 100
  keep_sparsity: False  
  sparsity: [0.0,0.0,0.0]
  # sparsity: [0.75,0.99,0.0]
  #lr_layer: [0.005,0.005,0.005]
  lr_layer: [0.5,0.5,0.5]
  f_target: 100
  
  c_reg: 0.01
  lr_win: 10
  classif: true
  gamma: 0.5
  e_lambda: 50
  weight_align: false
  use_buffer: false
  use_metapl: true
  use_ewc: false
  fr_reg: true
  # xi: 0.01
  xi: 20
  meta_func: 'exp'
  logit_reg: false

neuro-mnist:
  100:   
    dt: 1.0   
    lr: 0.0001

    


