default:
  optimizer: adam
  trasform: None
  # Continual learning From NEST
  alpha: 0.1
  lr: 0.0001
  n_epochs: 30
  batch_size: 32

  # SRNN architecture
  n_in: 1196
  srnn_hidden_size: 150
  n_out: 10
  thr: .6
  tau_m: 30
  tau_o: 100
  b_o: 0.0
  dt: 1.
  n_t: 100
  seq_len_train: 100
  seq_len_test: 100
  keep_sparsity: False  
  sparsity: [0.0,0.0,0.0]
  # sparsity: [0.75,0.99,0.0]
  lr_layer: [0.005,0.005,0.005]
  f_target: 10
  c_reg: 0
  lr_win: 10
  classif: true
  gamma: 0.5
  e_lambda: 0.5
  weight_align: false
  use_buffer: false
  use_metapl: false
  use_ewc: true 
  xi: 0.01
  logit_reg: false

neuro-mnist:
  100:   # Questo rappresenta il buffer_size o una configurazione specifica
    dt: 1.0   
    lr: 0.0001

    


